_target_: src.model.diffusion_unetcond_module.DiffusionUNetCondModule
unet:
  _target_: diffusers.UNet2DConditionModel
  in_channels: 7
  out_channels: 2
  sample_size: 64
  cross_attention_dim: 256

  block_out_channels: [224, 448, 672, 896]
  down_block_types: ["DownBlock2D", "AttnDownBlock2D", "CrossAttnDownBlock2D", "CrossAttnDownBlock2D"]
  up_block_types: ["CrossAttnUpBlock2D", "CrossAttnUpBlock2D", "CrossAttnUpBlock2D", "UpBlock2D"]

noise_scheduler:
  _target_: diffusers.DDPMScheduler
  num_train_timesteps: 100
  beta_schedule: "squaredcos_cap_v2"

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: ${base_lr}
  weight_decay: 0.01

encoder_model_params:
  in_channels: 4
  out_channels: 256
  cnn_layers: [64, 128, 256]
  