_target_: src.model.diffusion_unet_module.DiffusionUNetModule
unet:
  _target_: diffusers.UNet2DModel
  in_channels: 6
  out_channels: 3
  sample_size: 64

  block_out_channels: [224, 448, 672, 896, 1024, 1024]
  down_block_types: ["DownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D", "AttnDownBlock2D"]
  up_block_types: ["AttnUpBlock2D", "AttnUpBlock2D", "AttnUpBlock2D", "AttnUpBlock2D", "AttnUpBlock2D", "UpBlock2D"]

noise_scheduler:
  _target_: diffusers.DDPMScheduler
  num_train_timesteps: 100
  beta_schedule: "squaredcos_cap_v2"

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: ${base_lr}
  weight_decay: 0.01
  