_target_: src.model.diffusion_unet_module.DiffusionUNetModule
model:
  _target_: diffusers.UNet2DModel
  block_out_channels: [128, 256, 256]
  down_block_types: ["DownEncoderBlock2D", "DownEncoderBlock2D", "DownEncoderBlock2D"]
  in_channels: 1
  layers_per_block: 2
  norm_num_groups: 32
  out_channels: 1
  sample_size: 84
  scaling_factor: 0.18215
  up_block_types: ["UpDecoderBlock2D", "UpDecoderBlock2D", "UpDecoderBlock2D"]