defaults:
  - default

accelerator: gpu
devices: 1

callbacks:
  _target_: lightning.pytorch.callbacks.ModelCheckpoint
  dirpath: "checkpoints"
  monitor: val_loss
  mode: min
  save_top_k: 1
  save_last: true
  save_weights_only: true
  verbose: true