defaults:
    - _self_
    - data: mask_diffusion_data
    - model: diffusion_dit
    - trainer: gpu

seed: 42
num_workers: 4
batch_size: 64

# trainer
max_epochs: 100
check_val_every_n_epoch: 1

base_lr: 0.0001
end_lr: 0.000001
warmup_steps: 1000
decay_steps: 300000

image_size: 64
gpu_id: 1